In [51]:
from __future__ import absolute_import, division, print_function
from mayavi import mlab
import numpy as np
import math
import pandas as pd
from sklearn.preprocessing import normalize
import pyproj
import pptk
from ripser import ripser
from ripser import Rips

In [39]:
#random examples
def show_spheres():
    alpha = np.linspace(0, 2*math.pi, 100)  

    xs = np.cos(alpha)
    ys = np.sin(alpha)
    zs = np.zeros_like(xs)

    mlab.points3d(0,0,0)
    plt = mlab.points3d(xs[:1], ys[:1], zs[:1])

    @mlab.animate(delay=100)
    def anim():
        f = mlab.gcf()
        while True:
            for (x, y, z) in zip(xs, ys, zs):
                print('Updating scene...')
                plt.mlab_source.set(x=x, y=y, z=z)
                yield

    anim()
    mlab.show()
    
def show_dots():
    x, y, z, value = np.random.random((4, 40))
    mlab.points3d(x, y, z, value)
    mlab.show()
def show_sphere():
    mlab.clf()
    phi, theta = np.mgrid[0:np.pi:11j, 0:2*np.pi:11j]
    x = np.sin(phi) * np.cos(theta)
    y = np.sin(phi) * np.sin(theta)
    z = np.cos(phi)
    mlab.mesh(x, y, z)
    mlab.mesh(x, y, z, representation='wireframe', color=(0, 0, 0))
    mlab.show()
    
def show_surface():
    mlab.clf()
    x, y = np.mgrid[-10:10:100j, -10:10:100j]
    r = np.sqrt(x**2 + y**2)
    z = np.sin(r)/r
    mlab.surf(z, warp_scale='auto')
    mlab.show()

def test_points3d(long,lat,z):
    t = np.linspace(0, 4 * np.pi, 20)
    s = 1
    mlab.points3d(long, lat, z, colormap="copper", scale_factor=.25)   
    mlab.show()
# Our current dataset
def traffic_data(lat,long,alt):
    mlab.clf()
    xv, yv = np.meshgrid(lat, long)
    #r = np.sqrt(xv**2 + yv**2)
    z = np.sqrt(xv**2 + yv**2)
    mlab.mesh(xv, yv, z)
    mlab.mesh(xv, yv, z, representation='wireframe', color=(0, 0, 0))
    mlab.show()

In [40]:
#define the projection map
proj = pyproj.Proj(proj='utm', zone=50, ellps='WGS84')

#define the database
df = pd.read_csv("dataset_raw_full.csv")
df.head(400)

,Latitude,Longitude,Altitude,Date_Time,Id_user,Id_perc,Label
0,41.741415,86.186028,-777.0,2008-03-31 16:00:08,10,20080331160008.plt,taxi
1,41.737063,86.179470,-777.0,2008-03-31 16:01:07,10,20080331160008.plt,taxi
2,41.734105,86.172823,-777.0,2008-03-31 16:02:07,10,20080331160008.plt,taxi
3,41.739110,86.166563,-777.0,2008-03-31 16:03:06,10,20080331160008.plt,taxi
4,41.744368,86.159987,-777.0,2008-03-31 16:04:05,10,20080331160008.plt,taxi
...,...,...,...,...,...,...,...
395,39.474037,75.990490,4088.0,2008-04-02 06:22:41,10,20080402060926.plt,walk
396,39.474037,75.990477,4090.0,2008-04-02 06:22:42,10,20080402060926.plt,walk
397,39.474040,75.990462,4091.0,2008-04-02 06:22:43,10,20080402060926.plt,walk
398,39.474045,75.990448,4090.0,2008-04-02 06:22:44,10,20080402060926.plt,walk
399,39.474048,75.990437,4090.0,2008-04-02 06:22:45,10,20080402060926.plt,walk

In [41]:
#create categorical for each label in the dataframe
labels_cat = pd.Categorical(df.Label)
df['encoding'] = labels_cat.codes

#add convert the label data to integers
labels = df["Label"].drop_duplicates()
encodings = df["encoding"].drop_duplicates()
print(labels)

#create the map for each label in the data
label_map = dict(zip(labels, encodings))
print(label_map)

df.head(10)

0              taxi
22             walk
791             bus
1477          train
143449          car
203971     airplane
280608       subway
331763         bike
581929          run
1551126        boat
Name: Label, dtype: object
{'taxi': 7, 'walk': 9, 'bus': 3, 'train': 8, 'car': 4, 'airplane': 0, 'subway': 6, 'bike': 1, 'run': 5, 'boat': 2}

,Latitude,Longitude,Altitude,Date_Time,Id_user,Id_perc,Label,encoding
0,41.741415,86.186028,-777.0,2008-03-31 16:00:08,10,20080331160008.plt,taxi,7
1,41.737063,86.179470,-777.0,2008-03-31 16:01:07,10,20080331160008.plt,taxi,7
2,41.734105,86.172823,-777.0,2008-03-31 16:02:07,10,20080331160008.plt,taxi,7
3,41.739110,86.166563,-777.0,2008-03-31 16:03:06,10,20080331160008.plt,taxi,7
4,41.744368,86.159987,-777.0,2008-03-31 16:04:05,10,20080331160008.plt,taxi,7
5,41.744513,86.159808,-777.0,2008-03-31 16:05:04,10,20080331160008.plt,taxi,7
6,41.748142,86.155330,-777.0,2008-03-31 16:06:03,10,20080331160008.plt,taxi,7
7,41.749640,86.153458,-777.0,2008-03-31 16:07:02,10,20080331160008.plt,taxi,7
8,41.754737,86.148085,-777.0,2008-03-31 16:08:02,10,20080331160008.plt,taxi,7
9,41.758855,86.144468,-777.0,2008-03-31 16:09:01,10,20080331160008.plt,taxi,7

In [42]:
#get longitude, latitude, altitude from the dataframe
long = normalize([np.array(df["Longitude"].to_list())])
lat = normalize([np.array(df["Latitude"].to_list())])
alt = normalize([np.array(df["Altitude"].to_list())])

#create the metrics projection
x, y = proj(df['Longitude'].tolist(), df['Latitude'].tolist())

In [43]:
#create the projection array
P = np.c_[df['Longitude'].tolist(), df['Latitude'].tolist(),np.zeros(len(df))]

#define the pptviewr parameters to better visualize the data
#v = pptk.viewer(P)
#v.attributes(df['Altitude'])
#v.color_map('jet', scale=[0, 20000])

In [44]:
#filter the data witht the usefull point cluster
mask_51 = (df['Longitude'] > 115.5) & (df['Longitude'] < 116.7) & (df['Latitude'] > 39.5) & (df['Latitude'] < 40.25)
df1 = df[mask_51]

#create the projection 
x, y = proj(df1['Longitude'].tolist(), df1['Latitude'].tolist())
p = np.c_[x, y, 0.3048 * df1['Altitude']]  # alt originally in feet

#visualize the mask levels by the labels
mask_labelled = df1['encoding'] != 0
print(df1[mask_labelled]['encoding'])
#v = pptk.viewer(p[mask_labelled])
#v.attributes(df1[mask_labelled]['encoding'])

41880      3
41881      3
41882      3
41883      3
41884      3
          ..
3387298    3
3387299    3
3387300    3
3387301    3
3387302    3
Name: encoding, Length: 2818377, dtype: int8

In [45]:
def print_label(df2, label, long_s, long_f, lat_s, lat_f):
    mask_52 = (df['Longitude'] > long_s) & (df['Longitude'] < long_f) & (df['Latitude'] > lat_s) & (df['Latitude'] < lat_f) &(df1['encoding'] == label)
    df2 = df[mask_52]

    #create the projection 
    x, y = proj(df2['Longitude'].tolist(), df2['Latitude'].tolist())
    p = np.c_[x, y, 0.3048 * df2['Altitude']]  # alt originally in feet

    #visualize the mask levels by the labels
    mask_labelled = df2['encoding'] == label
    #print(df2[mask_labelled]['encoding'])
    v = pptk.viewer(p[mask_labelled])
    v.attributes(df2[mask_labelled]['encoding'])
    
def get_dataset_of_label(df2, label, long_s, long_f, lat_s, lat_f):
    mask_52 = (df['Longitude'] > long_s) & (df['Longitude'] < long_f) & (df['Latitude'] > lat_s) & (df['Latitude'] < lat_f) &(df1['encoding'] == label)
    df2 = df[mask_52]

    #create the projection 
    x, y = proj(df2['Longitude'].tolist(), df2['Latitude'].tolist())
    p = np.c_[x, y, 0.3048 * df2['Altitude']]  # alt originally in feet

    #visualize the mask levels by the labels
    mask_labelled = df2['encoding'] == label
    #print(df2[mask_labelled]['encoding'])
    return p[mask_labelled],df2[mask_labelled]['encoding']

In [46]:
#print_label(df, 3, 115.5, 116.7, 39.5, 40.25)
#print_label(df, 8, 115.5, 116.7, 39.5, 40.25)
#print_label(df, 4, 115.5, 116.7, 39.5, 40.25)
#print_label(df, 9, 115.5, 116.7, 39.5, 40.25)

In [47]:
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QSlider, QLabel, QWidget
from PyQt5.QtCore import Qt
import matplotlib
matplotlib.use('Qt5Agg')  # Use Qt5Agg backend
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.patches import Circle
import gudhi


class MainWindow(QMainWindow):
    def __init__(self,centers):
        super().__init__()

        self.setWindowTitle("Circle Visualization")
        self.setGeometry(200, 200, 600, 400)

        self.figure = Figure()
        self.canvas = FigureCanvas(self.figure)

        self.radius = 1
        #self.centers = [(1, 2), (4, 0), (2, 6), (8, 2), (8, 5), (6, 6), (7, 9), (12, 6), (11, 9)]
        self.centers = centers

        self.setup_ui()

    def setup_ui(self):
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        layout = QVBoxLayout(central_widget)

        layout.addWidget(self.canvas)

        # Slider
        self.slider = QSlider(Qt.Horizontal)
        self.slider.setMinimum(1)
        self.slider.setMaximum(50)
        self.slider.setValue(self.radius)
        self.slider.setTickPosition(QSlider.TicksBelow)
        self.slider.setTickInterval(1)
        self.slider.valueChanged.connect(self.on_slider_value_changed)
        layout.addWidget(self.slider)

        self.label = QLabel("Radius: {}".format(self.radius))
        layout.addWidget(self.label)

        self.update_graph()

    def update_graph(self):
        self.figure.clear()
        ax = self.figure.add_subplot(111)
        ax.clear()


        for center in self.centers:
            circle = Circle(center, self.radius/10, fill=False)
            ax.add_patch(circle)

        # Plot the center points
        x_centers = [center[0] for center in self.centers]
        y_centers = [center[1] for center in self.centers]
        ax.plot(x_centers, y_centers, 'ro')

        ax.set_aspect('equal')
        ax.autoscale()

        # Compute the Alpha complex
        points = [[center[0], center[1]] for center in self.centers]
        complex = gudhi.AlphaComplex(points)
        simplex_tree = complex.create_simplex_tree()
        alpha_skeleton = list(simplex_tree.get_skeleton(1))

        
        edges = [edge[0] for edge in alpha_skeleton]
        # Fill in missing edges with correct values
        
        for edge in edges:
            point1 = points[edge[0]]
            if len(edge)!=2:
                point2 = points[edge[0]]
            else:
                point2 = points[edge[1]]
            ax.plot([point1[0], point2[0]], [point1[1], point2[1]], 'b--')

        self.canvas.draw()
        # Clear previous plot
        


    def on_slider_value_changed(self):
        self.radius = self.slider.value()
        self.label.setText("Radius: {}".format(self.radius))
        self.update_graph()

In [48]:
p_3, enc_3 =get_dataset_of_label(df, 3, 115.5, 116.7, 39.5, 40.25)

#print(p_3)
#print(enc_3)
points = []
for point in p_3:
    points.append((point[0],point[1]))
    
print(points[0])

(441540.8878486032, 4416383.1539714)

In [52]:
centers = [(1, 2), (4, 0), (2, 6), (8, 2), (8, 5), (6, 6), (7, 9), (12, 6), (11, 9)]

points = points[:100]
rips = Rips()
diagrams = rips.fit_transform(points)
rips.plot(diagrams)


# app = QApplication(sys.argv)
# window = MainWindow(points)
# window.show()
# sys.exit(app.exec_())

[[  0.           1.45236874]
 [  0.           4.3959322 ]
 [  0.           4.73434925]
 [  0.           5.29814243]
 [  0.           6.46535254]
 [  0.           6.77627993]
 [  0.           7.76183558]
 [  0.          10.25952339]
 [  0.          10.52081299]
 [  0.          10.69024086]
 [  0.          11.92030811]
 [  0.          12.1842947 ]
 [  0.          13.87119865]
 [  0.          15.11246872]
 [  0.          17.22325897]
 [  0.          17.34259605]
 [  0.          17.64892006]
 [  0.          24.38036728]
 [  0.          24.40238762]
 [  0.          35.33224106]
 [  0.          43.85861588]
 [  0.          46.13795471]
 [  0.          46.37322998]
 [  0.          48.25457382]
 [  0.          50.10317612]
 [  0.          50.27386093]
 [  0.          56.42998886]
 [  0.          57.6195755 ]
 [  0.          63.44738388]
 [  0.          69.62362671]
 [  0.          70.36331177]
 [  0.          74.17102051]
 [  0.          75.37197113]
 [  0.          78.30259705]
 [  0.          78.65053558]
 [  0.          80.54938507]
 [  0.          82.97740936]
 [  0.          83.00522614]
 [  0.          84.2853241 ]
 [  0.          88.32884216]
 [  0.          88.70375061]
 [  0.          88.98683167]
 [  0.          89.33444977]
 [  0.          90.37763977]
 [  0.          90.47329712]
 [  0.          92.50527954]
 [  0.          96.41882324]
 [  0.          98.31472778]
 [  0.         103.12113953]
 [  0.         104.15990448]
 [  0.         104.31156158]
 [  0.         107.44181061]
 [  0.         107.61042786]
 [  0.         110.05966187]
 [  0.         114.73917389]
 [  0.         115.95402527]
 [  0.         116.87168884]
 [  0.         122.89130402]
 [  0.         123.91696167]
 [  0.         124.69334412]
 [  0.         127.57027435]
 [  0.         129.0218811 ]
 [  0.         133.22717285]
 [  0.         134.12487793]
 [  0.         134.14204407]
 [  0.         134.27853394]
 [  0.         136.28257751]
 [  0.         137.27832031]
 [  0.         141.1660614 ]
 [  0.         141.67512512]
 [  0.         141.82757568]
 [  0.         142.74049377]
 [  0.         143.69952393]
 [  0.         145.84825134]
 [  0.         148.373703  ]
 [  0.         158.52139282]
 [  0.         161.25552368]
 [  0.         161.88482666]
 [  0.         162.532547  ]
 [  0.         164.50221252]
 [  0.         168.45054626]
 [  0.         174.09796143]
 [  0.         199.4604187 ]
 [  0.         204.50886536]
 [  0.         209.09851074]
 [  0.         219.193573  ]
 [  0.         223.05581665]
 [  0.                  inf]]
[]